[package]
name = "graph-layout"
version.workspace = true
edition.workspace = true
repository.workspace = true
authors.workspace = true
description = "Generic graph layout algorithms"

[dependencies]
petgraph.workspace = true
thiserror.workspace = true
