name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.5
      - name: Run rusttmt
        run: cargo fmt --all --check
      - name: Install deps
        run: |
          sudo tar -xvf gstreamer-1.22-jammy-$(uname -m).tbz2 --strip-components=1 -C /usr/local
          sudo apt-get update && sudo apt-get install -y \
            bzip2 \
            ffmpeg \
            libfribidi0 \
            libgtk-3-dev \
            libharfbuzz0b \
            libsqlite3-0 \
            libssl3 \
            libthai0
          gst-launch-1.0 --version
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Build
        run: cargo build -v
      - name: Run tests
        run: cargo test -v
