name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check code fmt
      run: cargo fmt --all --check
    - name: Install deps
      run: |
        sudo tar -xvf gstreamer-1.22-jammy-$(uname -m).tbz2 --strip-components=1 -C /usr/local
        sudo apt-get update && sudo apt-get install -y \
          bzip2 \
          libavfilter7 \
          libharfbuzz0b \
          libfribidi0 \
          libthai0 \
          libsqlite3-0 \
          libssl3
        gst-launch-1.0 --version
    - name: Build
      run: cargo build -v
    - name: Run tests
      run: cargo test -v
